### ISSUE TITLE
Some discussions

### ISSUE THREAD

**Issue by noone-code** [zju3dv/LoFTR#12]
I try to match the image pairs in `issue` #7.
I don't agree with your answers in there.
> **JiamingSuen**: I would like to point out that LoFTR (and SuperGlue) learns the matching priors (i.e., the distribution of matches between the image pair) from the **training data**, which means that it can only handle rotations exhibited in the training set.

SuperGlue gives a so-so result, while LoFTR cannot find any matches.

### Result from LoFTR
![2f248914c476c1e4c2b19a1bcea826e](https://user-images.githubusercontent.com/74461548/115517308-96f1a380-a2b9-11eb-8c5e-86514d3f6558.png)
### Result from SuperGlue
![matches_000000_000001_0 2](https://user-images.githubusercontent.com/74461548/115517514-c7d1d880-a2b9-11eb-81fa-a4a1bd5b85c5.png)

**Comment by JiamingSuen** [comment]
I believe the reason is that the descriptors of SuperPoint have the ability to handle the most extreme rotations, benefiting from the large coverage of rotation range during its training with synthetic homography data. Even though SuperGlue and LoFTR are both trained on ScanNet with a smaller rotation range compared to synthetic homography, SuperGlue has better descriptors (in handling extreme rotations) from the very beginning of training.

We would like to point out that we never claimed that LoFTR is capable of handling extreme rotations and we recommend you check out other works (as suggested before, GIFT and LISRD) for this purpose.
