### ISSUE TITLE
the number of detect keypoints

### ISSUE THREAD

**Issue by szgy66** [zju3dv/LoFTR#129]
Hi,I want to calculate the Recall of the keypoints of match, but I just find the mkpts0/mkpts1 in the source, which means the matched keypoint if I'm not mistake. But  I don't find the detect keyponit, it show kpts0/kpts1 in the source. Where can I find it? Thanks a lot!

**Comment by zehongs** [comment]
Hi, there is no such concept as detected keypoints in LoFTR. 
The 1/8 grid points on the left image can be used to calculate the recall. You need to check if there's a valid correspondence on the right image for each points. A invalid correspondence might occur due to occlusion, invalid depth or incorrect depth, etc.

**Comment by abhimanyuchadha96** [comment]
@zehongs Could you elaborate on this?
`mkpts0/mkpts1` only returns the matched features.
How do we set a baseline during inference for the detected number of matches?

**Comment by zehongs** [comment]
Hi, len(mkpts0) equals len(mkpts1), so len(mkpts0) should represent the detected number of matches. 
Remember to use `bid` to set the mask for each pair in a batch https://github.com/zju3dv/LoFTR/blob/5d6c83428ab57987e5c4d42374b86e8b1f9cb520/src/utils/metrics.py#L64.
