### ISSUE TITLE
Question on bordering operation in CoarseMatching

### ISSUE THREAD

**Issue by codeslake** [zju3dv/LoFTR#15]
Hi, thanks for the fabulous work!

I was looking for works leveraging dense feature matching operations and ended up in this repository.
I am new to the feature matching task, so please be patient with me :)

1) What is the purpose of bordering the matching mask? (The [`mask_border()` function](https://github.com/zju3dv/LoFTR/blob/5e5c6fcc066bf4244e3c2df242c31d235a3dcde8/src/loftr/utils/coarse_matching.py#L143))

2) In the function, does indexing `[..-b:0..]` apply borders on any portion of tensors? If it is intended, I don't get the purpose of it.

Thanks!

**Comment by zehongs** [comment]
Hi, thanks!

We did this for two reasons. First of all, the undistorted images (e.g. [ScanNet image](https://github.com/zju3dv/LoFTR/blob/master/assets/scannet_sample_images/scene0711_00_frame-001680.jpg)) have black borders which may confuse the matching algorithm. Because they might exhibit some patterns. Secondly, we extract local features with CNN, so it's good to pay attention to the border effect (caused by zero-padding in convolution operation).

The function you mentioned masks the beginning and the ending w.r.t. every spatial dimensions.

**Comment by codeslake** [comment]
Hi, thanks for the kind reply :)

About the indexing, I believe `[-b:0]` does not pad anything. Did you mean `[-b: ]`?
Or, do ScanNet images have black borders on the top and left sides?

**Comment by zehongs** [comment]
Oh I think it is a bug. I’ll fix that! Many thanks!

**Comment by codeslake** [comment]
No worries!

I actually have another question on computing dense feature matching coordinates.

If I directly use the code, I believe I will have to set [`self.thr`](https://github.com/zju3dv/LoFTR/blob/5e5c6fcc066bf4244e3c2df242c31d235a3dcde8/src/loftr/utils/coarse_matching.py#L140), but I am not sure. If you have any other suggestions, would you please share your thoughts?

**Comment by zehongs** [comment]
Sorry for the late reply. For you question, I agree. Setting the `self.thr` to zero means using the MNN criterion only, which is strong enough under most circumstances.

**Comment by codeslake** [comment]
Alright, thanks for the reply!

**Comment by zehongs** [comment]
No problem!
