### ISSUE TITLE
想问下mask0和mask1是怎么用的

### ISSUE THREAD

**Issue by MickeymouseL** [zju3dv/LoFTR#207]
""" 
        Update:
            data (dict): {
                'image0': (torch.Tensor): (N, 1, H, W)
                'image1': (torch.Tensor): (N, 1, H, W)
                'mask0'(optional) : (torch.Tensor): (N, H, W) '0' indicates a padded position
                'mask1'(optional) : (torch.Tensor): (N, H, W)
            }
        """
上面的参数中，demo中的演示了image0和image1的用法，但是没有找到mask0和mask1的用法，我按上面的格式给到mask但是在linear_attention中这一步Q = Q * q_mask[:, :, None, None]会发送关于维度的问题
Traceback (most recent call last):
  File "<string>", line 1, in <module>
RuntimeError: The size of tensor a (7500) must match the size of tensor b (480000) at non-singleton dimension 1

能提供有关mask使用的demo吗

**Comment by MickeymouseL** [comment]
还有使用过程中发现，用0去给图片做填充，填充了0的位置也会产生特征点的匹配

**Comment by Varun-Tandon14** [comment]
@MickeymouseL You get the above error because the mask should be 1/8 scale of the (input)images. The actual format is 

image0': (torch.Tensor): (N, 1, H, W)
'image1': (torch.Tensor): (N, 1, H, W)
'mask0'(optional) : (torch.Tensor): (N, H/8, W/8) '0' indicates a padded position
'mask1'(optional) : (torch.Tensor): (N, H/8, W/8)

This is because the mask is applied during coarse matching where the feature size is 1/8 scale of the input. 

Additional note- If you use the Huggingface implementation of LoFTR you need not resize the mask (to 1/8 scale) because that implementation does resize before the masks are used in the coarse matching stage.  At this stage it's obvious but still writing for clarity that all the models based on this official repo like Quadtree attention, SE2-LoFTR will follow the same 1/8 (input image) scale for masks.
