### ISSUE TITLE
Can I send Batched Inputs to the model?

### ISSUE THREAD

**Issue by atharvjairath** [zju3dv/LoFTR#217]
Hi,
First of all amazing work with LoFTR!
I had a quick doubt, I want to compare 1 Image with N Images, is there any way where I can send pairs of them batched together 
in 1 inference run only? and if we can do it, can we also get the Number of matches of each pair?
would be glad if you can share the code example where we can stack/combine those image pairs together.
Thank you!

**Comment by zehongs** [comment]
Hi, Thanks,
Yes, please refer to the forward function of loftr
https://github.com/zju3dv/LoFTR/blob/2122156015b61fbb650e28b58a958e4d632b1058/src/loftr/loftr.py#L33-L36
Since matches between different pairs have different sizes. We need `b_id` to extract specific pair.
https://github.com/zju3dv/LoFTR/blob/2122156015b61fbb650e28b58a958e4d632b1058/src/utils/plotting.py#L69
I think you can get all helper variables in the updated `batch` dict.

**Comment by atharvjairath** [comment]
Thank you, I was able to batch the inputs.
