### ISSUE TITLE
Do different colors represent different accuracy rates in your demo?

### ISSUE THREAD

**Issue by Qing-WANG-KIT** [zju3dv/LoFTR#47]
Hi, first thanks for your great work.
In your demo, the matching lines have different colors. Do different colors represent different accuracy rates? For example, blue indicates that the point is accurately matched, and yellow indicates that the matching accuracy is relatively low?

**Comment by JiamingSuen** [comment]
No, color indicates the match confidence. Since the demo is recorded in a low-textured area, camera pose tracking (e.g. ARKit) could suffer from the low-textured inputs and produces inaccurate results. As a result, it's not easy to demonstrate the matching accuracy (e.g. epipolar distance) in the demo.

**Comment by Qing-WANG-KIT** [comment]
Thank you for your quick response! I understand what you mean.
