### ISSUE TITLE
Some quentions for focal loss

### ISSUE THREAD

**Issue by superluckyxhh** [zju3dv/LoFTR#53]
Hi. Why pos-conf and neg-conf all use 0.25 * (1-xxxconf)^2 * log(xxxconf)? 
neg-conf  means a bad match or one that doesn't need to be matched.Considering this reason. As neg-conf go down, the neg-loss as do.
But in the code,` loss_neg = - alpha * torch.pow(1 - neg_conf, gamma) * neg_conf.log()`, neg-conf decrease, the neg-loss will increase instaead?
Looking forward to your reply

**Comment by angshine** [comment]
For the sparse supervision with a sinkhorn matching layer, you could approximately think of it as a multi-class classification problem, like a `softmax-focal-loss` instead of `sigmoid-focal-loss`. For each coarse-level grid in the left view to be matched, there is one "target" in the right view that corresponds to it. This "target" could be a grid in the right view or just a dustbin (unmatchable). We extract those entries from the score matrix and apply focal-loss to them, whose scores/probabilities should be high instead of low, as you said. Maybe just forget about the positive & negative terms; we only supervise the positive terms in the sparse supervision case. The sinkhorn layer could naturally suppress the negative terms (which should have low scores).
